# Generated by Django 5.1.7 on 2025-04-12 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='given at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'reward log',
                'verbose_name_plural': 'reward logs',
                'ordering': ['-given_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('execute_at', models.DateTimeField(verbose_name='execute at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_rewards', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'scheduled reward',
                'verbose_name_plural': 'scheduled rewards',
                'ordering': ['-execute_at'],
            },
        ),
    ]
