# Generated by Django 5.1.7 on 2025-04-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRequestByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_user', to='rewards.scheduledreward', verbose_name='reward')),
            ],
            options={
                'verbose_name': 'reward request by user',
                'verbose_name_plural': 'reward requests by users',
            },
        ),
    ]
